window.alert("Hello! This is my first JavaScript alert.");
document.write("Hello! This is written directly on the page.");
let myMessage = "This is my string value!";
window.alert(myMessage);
let quoteExample = "She said, \"JavaScript is fun!\" and I couldn't agree more.";
window.alert(quoteExample);
let firstName = "Joseph";
document.write("Hello, " + firstName + "! Welcome to JavaScript.");
let result = 5 + 3 * 2;
document.write("<br>The result of the expression 5 + 3 * 2 is: " + result);